# NieRi-dots — fuzzel launcher config

[main]
font=JetBrainsMono Nerd Font:size=12
terminal=kitty
prompt="❯ "
icon-theme=Adwaita
lines=8
width=40
horizontal-pad=24
vertical-pad=16
inner-pad=8

[colors]
background=0a0611e6
text=cdd6f4ff
match=a277ffff
selection=15121fff
selection-text=cdd6f4ff
selection-match=a277ffff
border=a277ffff

[border]
width=2
radius=8
